Andrade.Chamados.Web/ViewModels/Chamado/ChamadoViewModel.cs
using Andrade.Chamado.Domain.Enum;
using Andrade.Chamados.Web.ViewModels.Usuario;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Andrade.Chamados.Web.ViewModels.Chamado
{
    public class ChamadoViewModel : BaseViewModel
    {

        public ChamadoViewModel()
        {
            ListaSetores = CarregaListaSetores();
            ListaStatus = CarregaListaStatus();
        }

        [Required(ErrorMessage="Título deve ser preenchido")]
        [Display(Name ="Título do chamado")]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "Informe a descrição do chamado")]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "Informe o setor")]
        public EnSetor Setor { get; set; }

        [Required(ErrorMessage = "Informe o status")]
        public EnStatus Status { get; set; }

        public Guid IdUsuario { get; set; }

        public virtual UsuarioViewModel Usuario { get; set; }

        public SelectList ListaSetores { get; set; }
        public SelectList ListaStatus { get; set; }


        /// <summary>
        /// Carrega lista de setores a partir de um Enum
        /// </summary>
        /// <returns> Retorna um SelectList com os setores </returns>
        public SelectList CarregaListaSetores()
        {
            var listaSetores = new SelectList(Enum.GetValues(typeof(EnSetor)).Cast<EnSetor>().Select(c =>
            new SelectListItem
            {
                Text = c.ToString(),
                Value = ((int)c).ToString()
           }).ToList(), "Value" , "Text");

            return listaSetores;
        }


        /// <summary>
        /// Carrega lista de status a partir de Enum
        /// </summary>
        /// <returns> Retorna um SelectList com os status </returns>
        public SelectList CarregaListaStatus()
        {
            var listaStatus = new SelectList(Enum.GetValues(typeof(EnStatus)).Cast<EnStatus>().Select(c =>
            new SelectListItem
            {
                Text = c.ToString(),
                Value = ((int)c).ToString()
            }).ToList(), "Value", "Text");

            return listaStatus;
        }



    }
}

Andrade.Chamados.Web/ViewModels/Chamado/ListaChamadoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Andrade.Chamados.Web.ViewModels.Chamado
{
    public class ListaChamadoViewModel
    {
        public List<ChamadoViewModel> ListaChamados { get; set; }
    }
}

Andrade.Chamados.Web/Controllers/ChamadoController.cs
using Andrade.Chamado.Domain.Entidades;
using Andrade.Chamados.Data.Repositorios;
using Andrade.Chamados.Web.ViewModels.Chamado;
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Principal;
using System.Web.Mvc;

namespace Andrade.Chamados.Web.Controllers
{
    [Authorize]
    public class ChamadoController : Controller
    {
        // GET: Chamado
        [HttpGet]
        public ActionResult Index()
        {
            ListaChamadoViewModel vmListaChamados = new ListaChamadoViewModel();

            using (ChamadoRepositorio _repChamado = new ChamadoRepositorio())
            {
                if (User.IsInRole("Administrador"))
                {
                    vmListaChamados.ListaChamados = Mapper.Map<List<ChamadoDomain>, List<ChamadoViewModel>>(_repChamado.Listar());
                }
                else
                {
                    var claims = User.Identity as ClaimsIdentity;
                    var id = claims.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

                    vmListaChamados.ListaChamados = Mapper.Map<List<ChamadoDomain>, List<ChamadoViewModel>>(_repChamado.Listar(new Guid(id)));
                }

               
            }

            return View(vmListaChamados);

        }


        [HttpGet]
        public ActionResult Cadastrar()
        {
            ChamadoViewModel vmChamado = new ChamadoViewModel();

            return View(vmChamado);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(ChamadoViewModel chamado)
        {

            try
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.Erro = " Dados invalidos";
                    return View(chamado);
                }

                using (ChamadoRepositorio _repChamado = new ChamadoRepositorio())
                {
                    var identity = User.Identity as ClaimsIdentity;
                    var id = identity.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
                    chamado.IdUsuario = new Guid(id);
                    _repChamado.Inserir(Mapper.Map<ChamadoViewModel, ChamadoDomain>(chamado));
                }

                TempData["Sucesso"] = " Chamado cadastrado...Aguarde!!!";
                return RedirectToAction("Index");
            }
            catch (System.Exception ex)
            {
                ViewBag.Erro = ex.Message;
                return View(chamado);
            }
        }
        
        [HttpGet]
        public ActionResult Editar(Guid? id)
        {
            ChamadoViewModel chamado = new ChamadoViewModel();

            try
            {

                if (id == null)
                {
                    TempData["Erro"] = " Id não identificado";
                    return RedirectToAction("Index");
                }

                using (ChamadoRepositorio _repChamado = new ChamadoRepositorio())
                {
                    chamado = Mapper.Map<ChamadoDomain, ChamadoViewModel>(_repChamado.BuscarPorId(id.Value));

                    if (chamado == null)
                    {
                        TempData["Erro"] = "Chamado não encontrado";
                        return RedirectToAction("Index");
                    }

                    #region Buscar Id usuário

                    var identity = User.Identity as ClaimsIdentity;
                    var idUsuario = identity.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

                    #endregion

                    if (User.IsInRole("Administrador") || idUsuario == chamado.IdUsuario.ToString())
                    {
                        return View(chamado);

                    }
                    else
                    {
                          TempData["Erro"] = " Este chamado pertence a outro usuário";
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (System.Exception ex)
            {
                ViewBag.Erro = ex.Message;
                return View(chamado);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(ChamadoViewModel chamado)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    ViewBag.Erro = " Dados inválidos";
                    return View(chamado);
                }

                using (ChamadoRepositorio _repChamado = new ChamadoRepositorio())
                {
                    _repChamado.Alterar(Mapper.Map<ChamadoViewModel, ChamadoDomain>(chamado));
                    TempData["Sucesso"] = " Chamado alterado";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {

                ViewBag.Erro = ex.Message;
                return View();
            }
        }


        [HttpGet]
        public ActionResult Excluir(Guid? id)
        {
            try
            {
                if (!User.IsInRole("Administrador"))
                {
                    TempData["Erro"] = " Você não tem permissão para excluir este chamado";
                    return RedirectToAction("Index");
                }

                if (id == null)
                {
                    TempData["Erro"] = " Informe o id do chamado";
                    return RedirectToAction("Index");
                }

                using (ChamadoRepositorio _repChamado = new ChamadoRepositorio())
                {
                    ChamadoViewModel chamado = Mapper.Map<ChamadoDomain, ChamadoViewModel>(_repChamado.BuscarPorId(id.Value));

                    if (chamado == null)
                    {
                        TempData["Erro"] = "Chamado não encontrado";
                        return RedirectToAction("Index");
                    }

                    #region Buscar Id usuário

                    var identity = User.Identity as ClaimsIdentity;
                    var idUsuario = identity.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

                    #endregion

                    if (User.IsInRole("Administrador") || idUsuario == chamado.IdUsuario.ToString())
                    {
                        return View(chamado);
                    }

                    TempData["Erro"] = "Você não possui permissão para excluir este chamado";
                    return RedirectToAction("Index");

                }
            }
            catch (Exception ex)
            {

                ViewBag.Erro = ex.Message;
                return View();
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Excluir(ChamadoViewModel chamado)
        {
            try
            {
                if (!User.IsInRole("Administrador"))
                {
                    TempData["Erro"] = " Você não tem permissão para excluir este chamado";
                    return RedirectToAction("Index");
                }

                if (chamado.Id == Guid.Empty)
                {
                    TempData["Erro"] = " Informe o id do chamado";
                    return RedirectToAction("Index");
                }

                using (ChamadoRepositorio _repChamado = new ChamadoRepositorio())
                {
                    ChamadoViewModel vmChamado = Mapper.Map<ChamadoDomain, ChamadoViewModel>(_repChamado.BuscarPorId(chamado.Id));
                    if (vmChamado == null)
                    {
                        TempData["Erro"] = "Chamado não encontrado";
                        return RedirectToAction("Index");
                    }

                    _repChamado.Deletar(Mapper.Map<ChamadoViewModel, ChamadoDomain>(vmChamado));
                    TempData["Sucesso"] = "Chamado excluido";
                    return RedirectToAction("Index");
                     
                }

            }
            catch (Exception ex)
            {
                ViewBag.Erro = ex.Message;
                return View(chamado);
            }
        }


    }
}

Andrade.Chamados.Web/Views/Chamado/Cadastrar.cshtml
@model Andrade.Chamados.Web.ViewModels.Chamado.ChamadoViewModel

@{
    /**/

    ViewBag.Title = "Cadastrar";
    Layout = "~/Views/Shared/_LayoutPage01.cshtml";
}

@section styles{
    <link href="http://getbootstrap.com/docs/4.1/examples/floating-labels/floating-labels.css" rel="stylesheet" />

}

@if (ViewBag.Erro != null)
{
    <div class="alert alert-danger">
        @ViewBag.Erro
    </div>
}



@using (Html.BeginForm("Cadastrar", "Chamado", new { @class = " form-singnin" }))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.AntiForgeryToken()

    <div class="text-center mb-4">
        <h1 class="h3 mb-3 font-weight-normal"> Cadastrar chamado</h1>
        <p> Cadstre um novo chamado</p>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Titulo)
        <br />
        @Html.TextBoxFor(x => x.Titulo, new { @class = "form-group" })
        @Html.ValidationMessageFor(x => x.Titulo, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Descricao)
        <br />
        @Html.TextAreaFor(x => x.Descricao, new { @class = "form-group" })
        @Html.ValidationMessageFor(x => x.Descricao, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Setor)
        @Html.DropDownListFor(x => x.Setor, Model.ListaSetores, "Selecione o setor", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Setor, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Status)
        @Html.DropDownListFor(x => x.Status, Model.ListaStatus, "Selecione o status", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Status, "", new { @class = "text-danger" })
    </div>

    <button type="submit" class="btn btn-lg btn-block btn-primary"> Criar </button>


}

Andrade.Chamados.Web/Views/Chamado/Editar.cshtml
@model Andrade.Chamados.Web.ViewModels.Chamado.ChamadoViewModel

@{
    /**/

    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_LayoutPage01.cshtml";
}

@section styles{
    <link href="http://getbootstrap.com/docs/4.1/examples/floating-labels/floating-labels.css" rel="stylesheet" />

}

@if (ViewBag.Erro != null)
{
    <div class="alert alert-danger">
        @ViewBag.Erro
    </div>
}



@using (Html.BeginForm("Editar", "Chamado", new { @class = " form-singnin" }))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.AntiForgeryToken()

    @Html.HiddenFor(x => x.Id)
    @Html.HiddenFor(x => x.IdUsuario)

    <div class="text-center mb-4">
        <h1 class="h3 mb-3 font-weight-normal"> Editar chamado</h1>
        <p> Edite um chamado</p>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Titulo)
        @Html.TextBoxFor(x => x.Titulo, new { @class = "form-group" })
        @Html.ValidationMessageFor(x => x.Titulo, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Descricao)
        @Html.TextAreaFor(x => x.Descricao, new { @class = "form-group" })
        @Html.ValidationMessageFor(x => x.Descricao, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Setor)
        @Html.DropDownListFor(x => x.Setor, Model.ListaSetores, "Selecione o setor", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Setor, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Status)
        @Html.DropDownListFor(x => x.Status, Model.ListaStatus, "Selecione o status", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Status, "", new { @class = "text-danger" })
    </div>

    <button type="submit" class="btn btn-lg btn-block btn-primary"> Criar </button>


}

Andrade.Chamados.Web/Views/Chamado/Excluir.cshtml
@model Andrade.Chamados.Web.ViewModels.Chamado.ChamadoViewModel

@{
    ViewBag.Title = "Excluir";
    Layout = "~/Views/Shared/_LayoutPage01.cshtml";
}

<h2>Excluir chamado</h2>

@using (Html.BeginForm("Excluir", "Chamado", FormMethod.Post))
{
    @Html.HiddenFor( x => x.Id)

    @Html.AntiForgeryToken()

    <br />
    <br />

    <p> Você realmente deseja excluir o chamado @Model.Titulo ?</p>
    <button class="btn btn-lg btn-primary btn-block" type="submit"> Excluir </button>

}

Andrade.Chamados.Web/Views/Chamado/Index.cshtml
@model Andrade.Chamados.Web.ViewModels.Chamado.ListaChamadoViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage01.cshtml";
}

<div class="jumbotron">
    <center>
        <div class="container">
            <h1> Tela de usuários</h1>
            <p> Visualize todo os usuários cadastrados no sistema</p>
            <p><a href="/Chamado/Cdastrar" class="btn btn-lg btn-primary" role="button"> Criar chamado</a> </p>
        </div>
    </center>
</div>

        @if (TempData["Erro"] != null)
        {
            <div class="alert alert-danger">
                @TempData["Erro"]
            </div>
        }

        @if (TempData["Sucesso"] != null)
        {
            <div class="alert alert-success">
                @TempData["Sucesso"]
            </div>
        }

        <table class="table">
            <thead>
                <tr>
                    <th> Título </th>
                    <th> Setor </th>
                    <th> Status </th>
                    <th> Data de criação </th>
                    <th>
                        
                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var chamado in Model.ListaChamados)
                {
                <tr>
                    <td> @Html.DisplayFor(x => chamado.Titulo)</td>
                    <td> @Html.DisplayFor(x => chamado.Setor)</td>
                    <td> @Html.DisplayFor(x => chamado.Status)</td>
                    <td> @Html.DisplayFor(x => chamado.DataCriacao)</td>
                    <td>
                        <a class="btn btn-primary" href="/Chamado/Editar/@chamado.Id"> <i class="glyphicon glyphicon-edit"></i> </a> &nbsp; &nbsp;

                        @if (User.IsInRole("Administrador"))
                        {
                            <a class="btn btn-danger" href="/Chamado/Excluir/@chamado.Id"><i class="glyphicon glyphicon-trash"></i> </a>
                        }

                    </td>
                    
                </tr>
                }
            </tbody>
        </table>

 